### ISSUE TITLE
Cannot upload jpeg images of 1.5M

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/profile-image-crop#15]
## Bug Report

**Current Behavior**
When uploading a jpeg image that should in theory not be too big (1.5M), then the backend returns an error saying that the file is too big.

**Steps to Reproduce**
1. Try to upload the following image 
https://user-images.githubusercontent.com/18526076/135299800-fa6f0ffe-3933-4336-9ae1-dff5e08e8fab.jpg

**Expected Behavior**
No error, as when disabling the extension, the same image can actually be uploaded as avatar.

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.0
- PHP version: 8.0
- Browser: Latest Firefox

**Possible solution(s)**
Consider what is said in https://github.com/fengyuanchen/cropperjs#readme : 

> Known image size increase: When exporting the cropped image on the browser side with the HTMLCanvasElement.toDataURL method, the size of the exported image may be greater than the original image's. This is because the type of the exported image is not the same as the original image. So just pass the original image's type as the first parameter to toDataURL to fix this. For example, if the original type is JPEG, then use cropper.getCroppedCanvas().toDataURL('image/jpeg') to export image.

**Comment by clarkwinkelmann** [comment]
Do you know how big is the request in the developer tools?

I'm not really sure what we can do. It seems like we already export the file in the same format as the source, so I assume the problem isn't JPEG to PNG

https://github.com/FriendsOfFlarum/profile-image-crop/blob/70a41460ecc557aa793276585a7ffaec4962ba29/js/src/forum/components/ProfileImageCropModal.js#L92

Maybe it has something to do with JPEG quality which cannot be controlled with canvas? (or can it?)

If the size increase isn't much, the easiest solution is probably just to increase the server max upload size by a few %...

We could also add client-side size validation, but would it really make the error handling any better?

**Comment by iPurpl3x** [comment]
@clarkwinkelmann `Content-Length: 12606933`. (12.6 MB), so almost 10 times bigger!

**Comment by iPurpl3x** [comment]
When disabling the extension and uploading the same image, it works and `Content-Length: 1478115`

**Comment by clarkwinkelmann** [comment]
Wow, that's definitely a lot. I assume this might be because it creates a 100% quality JPEG. I wonder if we can customize the quality to be at most the same as the original, or maybe a hard-coded upper value.

**Comment by iPurpl3x** [comment]
Yes I hope it possible to do something. Else maybe another library should be used?...
